services:
  mongodb:
    image: mongo:latest   
    container_name: mongodb
    command: mongod --auth
    ports:
      - "27018:27017"      
    networks:
      - riot_network    
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}    
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db  
    restart: always          


  riotservice:
    build: ./RiotService
    container_name: riotservice
    image: dorilann/riotservice:latest
    ports:
      - "8000:8080"
    networks:
      - riot_network

  storageservice:
    build: ./StorageService
    container_name: storageservice
    image: dorilann/storageservice:latest
    ports:
      - "8001:8080"
    environment:
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
    networks:
      - riot_network
    depends_on:
      - mongodb
      - riotservice

  apigateway:
    build: ./ApiGateway
    container_name: apigateway
    image: dorilann/apigateway:latest
    ports:
      - "8002:8080"
    networks:
      - riot_network
    depends_on:
      - riotservice
      - storageservice

  frontend:
    build: ./frontend 
    container_name: frontend
    image: dorilann/frontend:latest
    ports:
      - "3000:3000"
    networks:
      - riot_network
    depends_on:
      - apigateway

  
  
networks:
  riot_network:
    driver: bridge

volumes:
  mongo-data:
