services:
  mongodb:
    image: mongo:latest   
    container_name: mongodb
    command: mongod --auth
    ports:
      - "27018:27017"      
    networks:
      - weather_network    
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}    
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db  
    restart: always          


  weatherservice:
    build: ./WeatherServiceTest
    container_name: weatherservice
    image: dorilann/weatherservicetest:latest
    ports:
      - "8000:8080"
    networks:
      - weather_network

  storageservice:
    build: ./StorageService
    container_name: storageservice
    image: dorilann/storageservice:latest
    ports:
      - "8001:8080"
    environment:
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
    networks:
      - weather_network
    depends_on:
      - mongodb
      - weatherservice

  apigateway:
    build: ./ApiGateway
    container_name: apigateway
    image: dorilann/apigateway:latest
    ports:
      - "8082:80"
    networks:
      - weather_network
    depends_on:
      - weatherservice
      - storageservice

  
  
networks:
  weather_network:
    driver: bridge

volumes:
  mongo-data:
